 #### roles criadas ####
- name: fflch.sambadc
  src: https://github.com/fflch/ansible-role-sambadc.git
  version: 1.0.9

- name: uspdev.sssd_ad
  src: https://github.com/uspdev/ansible-role-sssd-ad.git
  version: 1.0.1

 #### roles comunidade ####
- src: Stouts.hostname
- src: adriagalin.timezone
- src: infOpen.locales
- src: geerlingguy.ntp
- src: blackstar257.resolv

