 #### roles criadas ####
- name: fflch.sambadc
  src: https://github.com/fflch/ansible-role-sambadc.git
  version: 1.0.9

- name: fflch.domain-member
  src: https://github.com/fflch/ansible-role-domain-member.git
  version: 1.0.4

 #### roles comunidade ####
- src: Stouts.hostname
- src: adriagalin.timezone
- src: infOpen.locales
- src: geerlingguy.ntp
- src: blackstar257.resolv

